server:
  port: 30007

spring:
  application:
    name: api-gateway
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@oracle-db.vibraguard.svc.cluster.local:1521:xe}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME:system}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # H2 console removed as we are using Oracle now
