server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0

        - id: technicians-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/iot/technicians/**
          filters:
            - StripPrefix=0

        - id: motor-service
          uri: ${MOTOR_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/iot/motors/**, /api/v1/search/**
          filters:
            - StripPrefix=0

        - id: alert-service
          uri: ${ALERT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/ml/alerts/**
          filters:
            - StripPrefix=0

        - id: workorder-service
          uri: ${WORKORDER_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/iot/work-orders/**
          filters:
            - StripPrefix=0

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/v1/iot/inventory-parts/**
          filters:
            - StripPrefix=0

        - id: blockchain-service
          uri: ${BLOCKCHAIN_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/blockchain/**
          filters:
            - StripPrefix=0

        - id: blockchain-service-reports
          uri: ${BLOCKCHAIN_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/reports/**
          filters:
            - StripPrefix=0

        - id: bi-service
          uri: ${BI_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/bi/**
          filters:
            - StripPrefix=0

        - id: motor-service-ws
          uri: ws://${MOTOR_SERVICE_HOST:localhost}:8082
          predicates:
            - Path=/ws/vibrations

        - id: alert-service-ws
          uri: ws://${ALERT_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/ws/alerts

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://jaeger:4318/v1/traces}
