apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: vibraguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vibraguard-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:oracle:thin:@oracle-db.vibraguard.svc.cluster.local:1521:xe"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: oracle-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oracle-db-credentials
                  key: password
