server:
  port: 8081

spring:
  application:
    name: iot-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

mqtt:
  broker: tcp://localhost:1883
  topic: sensors/vibration
  client-id: iot-service-collector
